language: node_js
node_js:
  - 10
cache: npm
branches:
  only:
    - master
before_script:
  - npm install -g firebase-tools
  - cd functions && npm ci
script:
  - npm run lint
  - npm run test:ci
  - cd ..
after_success:
  - firebase deploy --force --only functions --token $FIREBASE_TOKEN

# deploy:
#   provider: firebase
#   edge: true
#   project: what-s-on-aristocrats
#   only: functions
#   token: $FIREBASE_TOKEN
