language: node_js
node_js:
  - 10
cache: npm
branches:
  only:
    - master
before_script:
  - yarn global add firebase-tools
  - cd functions && yarn install
script:
  - yarn lint
  # - yarn test:ci
  - cd ..
  - yarn docs:build # npm run docs:build
after_success:
  - firebase deploy --force --only functions --token $FIREBASE_TOKEN
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: $GITHUB_TOKEN # A token generated on GitHub allowing Travis to push code on you repository. Set in the Travis settings page of your repository, as a secure variable
  keep_history: true
  allow_empty_commit: true
  email: v.parakonnyi@gmail.com
  on:
    branch: master
